#!/bin/sh
while read file
do
        case "$1" in
        "C-s")
                cp "$file" ~/.config/wallpaper
                xwallpaper --zoom ~/.config/wallpaper
                ;;
        # "C-d")
        #         mv "$file" ~/.trash ;;
        # "C-r")
        #         convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        esac
done
